import json
from pipeline.steps.base import BaseStep
from pipeline.engine import PipelineContext
from pipeline.orchestrator import build_market_constraint, run_debate_panel, _log

class AgentDebateStep(BaseStep):
    @property
    def name(self) -> str:
        return "agents"

    def get_log_step(self) -> str:
        return "DEBATE_PANEL"

    def execute(self, context: PipelineContext) -> None:
        db = context.db
        run_id = context.run_id

        if not context.shared_data.get("context"):
            raise ValueError(f"Run {run_id} missing shared research context")

        shared_context = context.shared_data["context"]
        market_constraint = build_market_constraint(context.enabled_markets)
        
        result = run_debate_panel(
            db, run_id, shared_context, market_constraint,
            investment_focus=context.investment_focus, enabled_markets=context.enabled_markets,
            run_lessons=context.lessons,
        )
        
        proposals_log, fitness_map = result if isinstance(result, tuple) else (result, {})

        if not proposals_log:
            raise ValueError("No proposals generated by agents")

        context.shared_data["proposals_json"] = {"proposals": proposals_log, "fitness_map": fitness_map}
        context.save_to_db()
        
        _log(db, run_id, self.get_log_step(), "IN_PROGRESS", f"Collected {len(proposals_log)} proposals")
